## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_counts = application_df.nunique()
unique_counts

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [6]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
application_type_counts.rename_axis('APPLICATION_TYPE').reset_index(name='count').set_index('APPLICATION_TYPE')['count']

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts[classification_counts > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 100
classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      669
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [13]:
# Split our preprocessed data into our features and target arrays
X = application_df.drop(columns=['IS_SUCCESSFUL']).values
y = application_df['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [15]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_dim = X_train_scaled.shape[1]

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=input_dim))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

c:\Users\jacob\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 80)             │         4,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 30)             │         2,430 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            31 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,461 (25.24 KB)

 Trainable params: 6,461 (25.24 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
# Train the model
history = nn.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.6805 - loss: 0.6023 - val_accuracy: 0.7358 - val_loss: 0.5467
Epoch 2/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 865us/step - accuracy: 0.7318 - loss: 0.5504 - val_accuracy: 0.7314 - val_loss: 0.5489
Epoch 3/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7320 - loss: 0.5481 - val_accuracy: 0.7372 - val_loss: 0.5425
Epoch 4/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 890us/step - accuracy: 0.7316 - loss: 0.5487 - val_accuracy: 0.7372 - val_loss: 0.5466
Epoch 5/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 868us/step - accuracy: 0.7299 - loss: 0.5493 - val_accuracy: 0.7409 - val_loss: 0.5449
Epoch 6/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 891us/step - accuracy: 0.7337 - loss: 0.5439 - val_accuracy: 0.7354 - val_loss: 0.5442
Epoch 7/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 893us/step - accuracy: 0.7299 - loss: 0.5477 - val_accuracy: 0.7382 - val_loss: 0.5424
Epoch 8/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 944us/step - accuracy: 0.7336 - loss: 0.5440 - val_accuracy: 0.7394 - val_loss: 0.5460
Epoch 9/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 866us/step - accuracy: 0.7350 - loss: 0.5432 - val_accuracy: 0.7382 - val_loss: 0.5413
Epoch 10/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 870us/step - accuracy: 0.7277 - loss: 0.5466 - val_accuracy: 0.7385 - val_loss: 0.5426
Epoch 11/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7277 - loss: 0.5442 - val_accuracy: 0.7372 - val_loss: 0.5473
Epoch 12/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 882us/step - accuracy: 0.7280 - loss: 0.5493 - val_accuracy: 0.7398 - val_loss: 0.5425
Epoch 13/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.7392 - loss: 0.5333 - val_accuracy: 0.7400 - val_loss: 0.5423
Epoch 14/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 863us/step - accuracy: 0.7361 - loss: 0.5403 - val_accuracy: 0.7358 - val_loss: 0.5418
Epoch 15/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 863us/step - accuracy: 0.7390 - loss: 0.5385 - val_accuracy: 0.7372 - val_loss: 0.5431
Epoch 16/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 0.7364 - loss: 0.5402 - val_accuracy: 0.7378 - val_loss: 0.5421
Epoch 17/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 914us/step - accuracy: 0.7336 - loss: 0.5405 - val_accuracy: 0.7389 - val_loss: 0.5443
Epoch 18/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 891us/step - accuracy: 0.7306 - loss: 0.5432 - val_accuracy: 0.7392 - val_loss: 0.5387
Epoch 19/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 877us/step - accuracy: 0.7327 - loss: 0.5406 - val_accuracy: 0.7378 - val_loss: 0.5431
Epoch 20/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 886us/step - accuracy: 0.7400 - loss: 0.5351 - val_accuracy: 0.7383 - val_loss: 0.5431
Epoch 21/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7363 - loss: 0.5357 - val_accuracy: 0.7387 - val_loss: 0.5421
Epoch 22/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 890us/step - accuracy: 0.7370 - loss: 0.5408 - val_accuracy: 0.7396 - val_loss: 0.5411
Epoch 23/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 882us/step - accuracy: 0.7367 - loss: 0.5388 - val_accuracy: 0.7400 - val_loss: 0.5405
Epoch 24/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 864us/step - accuracy: 0.7323 - loss: 0.5433 - val_accuracy: 0.7363 - val_loss: 0.5418
Epoch 25/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 946us/step - accuracy: 0.7348 - loss: 0.5409 - val_accuracy: 0.7403 - val_loss: 0.5390
Epoch 26/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 960us/step - accuracy: 0.7324 - loss: 0.5415 - val_accuracy: 0.7392 - val_loss: 0.5406
Epoch 27/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 968us/step - accuracy: 0.7340 - loss: 0.5419 - val_accuracy: 0.7382 - val_loss: 0.5424
Epoch 28/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 882us/step - accuracy: 0.7391 - loss: 0.5380 - val_accuracy: 0.7354 - val_loss: 0.5449
Epoch 29/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 964us/step - accuracy: 0.7378 - loss: 0.5385 - val_accuracy: 0.7394 - val_loss: 0.5414
Epoch 30/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 965us/step - accuracy: 0.7361 - loss: 0.5369 - val_accuracy: 0.7365 - val_loss: 0.5436
Epoch 31/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 862us/step - accuracy: 0.7393 - loss: 0.5364 - val_accuracy: 0.7371 - val_loss: 0.5413
Epoch 32/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 922us/step - accuracy: 0.7343 - loss: 0.5405 - val_accuracy: 0.7382 - val_loss: 0.5397
Epoch 33/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 869us/step - accuracy: 0.7420 - loss: 0.5321 - val_accuracy: 0.7392 - val_loss: 0.5406
Epoch 34/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 965us/step - accuracy: 0.7372 - loss: 0.5351 - val_accuracy: 0.7400 - val_loss: 0.5396
Epoch 35/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 867us/step - accuracy: 0.7370 - loss: 0.5375 - val_accuracy: 0.7382 - val_loss: 0.5426
Epoch 36/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7425 - loss: 0.5300 - val_accuracy: 0.7398 - val_loss: 0.5414
Epoch 37/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 861us/step - accuracy: 0.7374 - loss: 0.5374 - val_accuracy: 0.7374 - val_loss: 0.5427
Epoch 38/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 860us/step - accuracy: 0.7390 - loss: 0.5343 - val_accuracy: 0.7387 - val_loss: 0.5406
Epoch 39/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 881us/step - accuracy: 0.7369 - loss: 0.5368 - val_accuracy: 0.7400 - val_loss: 0.5427
Epoch 40/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 861us/step - accuracy: 0.7336 - loss: 0.5405 - val_accuracy: 0.7382 - val_loss: 0.5418
Epoch 41/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 881us/step - accuracy: 0.7348 - loss: 0.5389 - val_accuracy: 0.7380 - val_loss: 0.5413
Epoch 42/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 873us/step - accuracy: 0.7384 - loss: 0.5338 - val_accuracy: 0.7402 - val_loss: 0.5424
Epoch 43/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.7380 - loss: 0.5363 - val_accuracy: 0.7382 - val_loss: 0.5402
Epoch 44/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 884us/step - accuracy: 0.7384 - loss: 0.5338 - val_accuracy: 0.7298 - val_loss: 0.5454
Epoch 45/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 858us/step - accuracy: 0.7343 - loss: 0.5314 - val_accuracy: 0.7402 - val_loss: 0.5409
Epoch 46/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 866us/step - accuracy: 0.7330 - loss: 0.5418 - val_accuracy: 0.7385 - val_loss: 0.5416
Epoch 47/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 911us/step - accuracy: 0.7389 - loss: 0.5318 - val_accuracy: 0.7382 - val_loss: 0.5440
Epoch 48/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 872us/step - accuracy: 0.7417 - loss: 0.5320 - val_accuracy: 0.7380 - val_loss: 0.5428
Epoch 49/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 868us/step - accuracy: 0.7362 - loss: 0.5395 - val_accuracy: 0.7371 - val_loss: 0.5454
Epoch 50/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 858us/step - accuracy: 0.7396 - loss: 0.5351 - val_accuracy: 0.7387 - val_loss: 0.5429
Epoch 51/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7419 - loss: 0.5322 - val_accuracy: 0.7409 - val_loss: 0.5435
Epoch 52/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 853us/step - accuracy: 0.7418 - loss: 0.5301 - val_accuracy: 0.7383 - val_loss: 0.5410
Epoch 53/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 855us/step - accuracy: 0.7342 - loss: 0.5354 - val_accuracy: 0.7413 - val_loss: 0.5443
Epoch 54/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 856us/step - accuracy: 0.7354 - loss: 0.5389 - val_accuracy: 0.7394 - val_loss: 0.5427
Epoch 55/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7370 - loss: 0.5371 - val_accuracy: 0.7394 - val_loss: 0.5422
Epoch 56/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7320 - loss: 0.5379 - val_accuracy: 0.7402 - val_loss: 0.5408
Epoch 57/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 907us/step - accuracy: 0.7367 - loss: 0.5352 - val_accuracy: 0.7391 - val_loss: 0.5411
Epoch 58/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7361 - loss: 0.5366 - val_accuracy: 0.7392 - val_loss: 0.5438
Epoch 59/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 892us/step - accuracy: 0.7421 - loss: 0.5306 - val_accuracy: 0.7387 - val_loss: 0.5429
Epoch 60/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 916us/step - accuracy: 0.7400 - loss: 0.5305 - val_accuracy: 0.7402 - val_loss: 0.5426
Epoch 61/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 908us/step - accuracy: 0.7425 - loss: 0.5278 - val_accuracy: 0.7383 - val_loss: 0.5438
Epoch 62/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7379 - loss: 0.5329 - val_accuracy: 0.7394 - val_loss: 0.5412
Epoch 63/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 877us/step - accuracy: 0.7410 - loss: 0.5346 - val_accuracy: 0.7385 - val_loss: 0.5432
Epoch 64/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 870us/step - accuracy: 0.7347 - loss: 0.5348 - val_accuracy: 0.7394 - val_loss: 0.5415
Epoch 65/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 876us/step - accuracy: 0.7416 - loss: 0.5326 - val_accuracy: 0.7392 - val_loss: 0.5410
Epoch 66/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 904us/step - accuracy: 0.7341 - loss: 0.5357 - val_accuracy: 0.7387 - val_loss: 0.5408
Epoch 67/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 880us/step - accuracy: 0.7410 - loss: 0.5322 - val_accuracy: 0.7351 - val_loss: 0.5444
Epoch 68/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - accuracy: 0.7375 - loss: 0.5300 - val_accuracy: 0.7409 - val_loss: 0.5416
Epoch 69/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 869us/step - accuracy: 0.7402 - loss: 0.5294 - val_accuracy: 0.7391 - val_loss: 0.5426
Epoch 70/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 903us/step - accuracy: 0.7439 - loss: 0.5314 - val_accuracy: 0.7380 - val_loss: 0.5443
Epoch 71/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 880us/step - accuracy: 0.7416 - loss: 0.5293 - val_accuracy: 0.7394 - val_loss: 0.5422
Epoch 72/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 870us/step - accuracy: 0.7310 - loss: 0.5393 - val_accuracy: 0.7394 - val_loss: 0.5440
Epoch 73/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 876us/step - accuracy: 0.7314 - loss: 0.5375 - val_accuracy: 0.7400 - val_loss: 0.5413
Epoch 74/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 955us/step - accuracy: 0.7350 - loss: 0.5362 - val_accuracy: 0.7407 - val_loss: 0.5419
Epoch 75/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 879us/step - accuracy: 0.7427 - loss: 0.5285 - val_accuracy: 0.7396 - val_loss: 0.5434
Epoch 76/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 950us/step - accuracy: 0.7313 - loss: 0.5384 - val_accuracy: 0.7385 - val_loss: 0.5424
Epoch 77/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 860us/step - accuracy: 0.7400 - loss: 0.5286 - val_accuracy: 0.7394 - val_loss: 0.5418
Epoch 78/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7366 - loss: 0.5341 - val_accuracy: 0.7402 - val_loss: 0.5423
Epoch 79/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 874us/step - accuracy: 0.7361 - loss: 0.5350 - val_accuracy: 0.7403 - val_loss: 0.5419
Epoch 80/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 856us/step - accuracy: 0.7356 - loss: 0.5349 - val_accuracy: 0.7387 - val_loss: 0.5427
Epoch 81/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 866us/step - accuracy: 0.7350 - loss: 0.5351 - val_accuracy: 0.7402 - val_loss: 0.5423
Epoch 82/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 886us/step - accuracy: 0.7418 - loss: 0.5290 - val_accuracy: 0.7365 - val_loss: 0.5443
Epoch 83/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 860us/step - accuracy: 0.7401 - loss: 0.5316 - val_accuracy: 0.7396 - val_loss: 0.5425
Epoch 84/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 859us/step - accuracy: 0.7373 - loss: 0.5305 - val_accuracy: 0.7387 - val_loss: 0.5420
Epoch 85/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 852us/step - accuracy: 0.7417 - loss: 0.5272 - val_accuracy: 0.7411 - val_loss: 0.5415
Epoch 86/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 891us/step - accuracy: 0.7339 - loss: 0.5352 - val_accuracy: 0.7425 - val_loss: 0.5428
Epoch 87/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 862us/step - accuracy: 0.7389 - loss: 0.5321 - val_accuracy: 0.7416 - val_loss: 0.5422
Epoch 88/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 888us/step - accuracy: 0.7383 - loss: 0.5323 - val_accuracy: 0.7407 - val_loss: 0.5429
Epoch 89/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 868us/step - accuracy: 0.7376 - loss: 0.5336 - val_accuracy: 0.7409 - val_loss: 0.5438
Epoch 90/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 927us/step - accuracy: 0.7409 - loss: 0.5314 - val_accuracy: 0.7405 - val_loss: 0.5414
Epoch 91/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 886us/step - accuracy: 0.7468 - loss: 0.5236 - val_accuracy: 0.7385 - val_loss: 0.5434
Epoch 92/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 901us/step - accuracy: 0.7392 - loss: 0.5334 - val_accuracy: 0.7414 - val_loss: 0.5432
Epoch 93/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 984us/step - accuracy: 0.7416 - loss: 0.5317 - val_accuracy: 0.7389 - val_loss: 0.5454
Epoch 94/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 883us/step - accuracy: 0.7369 - loss: 0.5306 - val_accuracy: 0.7400 - val_loss: 0.5428
Epoch 95/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 895us/step - accuracy: 0.7381 - loss: 0.5308 - val_accuracy: 0.7405 - val_loss: 0.5440
Epoch 96/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 912us/step - accuracy: 0.7396 - loss: 0.5304 - val_accuracy: 0.7402 - val_loss: 0.5451
Epoch 97/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 905us/step - accuracy: 0.7389 - loss: 0.5306 - val_accuracy: 0.7396 - val_loss: 0.5445
Epoch 98/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 859us/step - accuracy: 0.7423 - loss: 0.5292 - val_accuracy: 0.7387 - val_loss: 0.5456
Epoch 99/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 925us/step - accuracy: 0.7432 - loss: 0.5258 - val_accuracy: 0.7385 - val_loss: 0.5451
Epoch 100/100
686/686 ━━━━━━━━━━━━━━━━━━━━ 1s 917us/step - accuracy: 0.7405 - loss: 0.5311 - val_accuracy: 0.7411 - val_loss: 0.5467

In [18]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 612us/step - accuracy: 0.7273 - loss: 0.5625
Loss: 0.5624760985374451, Accuracy: 0.7272594571113586

In [19]:
# Export our model to HDF5 file
nn.save("trained_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.